version: '3.5'

services:
  files:
    image: nginx
    container_name: nginx
    ports:
      - 82:80
      - 443:443
    volumes:
      - /data-pool/containers/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /:/data
    restart: unless-stopped
