version: '3.5'

services:
  files:
    image: nginx
    container_name: files
    hostname: files.local
    ports:
      - 82:80
      - 443:443
    volumes:
      - /data/files/config/nginx.conf:/etc/nginx/nginx.conf
      - /data:/data
    restart: unless-stopped
