version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data-pool/containers/heimdall/config:/config
    ports:
      - 80:80
      - 444:443
    restart: unless-stopped
