services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /data-pool/containers/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/zigbee:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host
