mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /data-pool/containers/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    hostname: mosquitto.local
    networks:
      smarthome:
        external: true
        aliases:
          - mosquitto.local
