version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /mnt/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
