version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.2
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/data/torrent/watch:/watch
      - /media/data/torrent/downloads:/downloads
      - /data-pool/containers/torrent/config:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
