services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /data-pool/containers/vaultwarden/data:/data
    ports:
      - 83:80
      - 3012:3012
    environment:
      - DOMAIN=https://homeserver
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=qp!qUM*bgYPDMQvt2vy-
      - SENDS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=false
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=false
